# -*- coding: utf-8 -*-
"""Han Myrda - QPA_QRM_w2_pandas-basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18XI6Lq5YPm5ldtmhk5zsh03NBrCq-ibU
"""

import pandas as pd

df1=pd.read_csv("https://raw.githubusercontent.com/bartpiel/files-for-classes/refs/heads/main/Democracy_Index_4.csv")

# Select the first 10 rows
df1.head(10)

# Select the last 10 rows
df1.tail(10)

# Select random 10 rows
df1.sample(10)

# Provide names of all columns
df1.columns

# Calculate mean for column '2018'
df1['2018'].mean()

# Calculate median for column '2018'
df1['2018'].median()

# Provide basic statistics for your data frame
df1.describe()

# Provide unique values for 'Regime type' column
df1["Regime type"].unique()

# Drop column '2006'
df1=df1.drop(columns=["2006"])
df1.columns

# Create a new column
df1["diff_2022_2008"]=df1["2022"]-df1["2008"]
df1.head(5)

# Create a new data frame
df2=df1[['Country','2022','2021']]
df2.head(10)

# Save your new data frame as a CSV file
df2.to_csv("df2.csv")

"""### Tasks for students

1. Create the df4 data frame from this url https://raw.githubusercontent.com/bartpiel/files-for-classes/refs/heads/main/Workshop-1/S1_Student_Grades_2.csv
2. Check its first 7 rows
3. Check 9 random rows of df4
4. Create a list of all df4 columns
5. Calculate the mean of the 'S1_Grade' column.
6. Calculate the median of the 'S4_Grade' column.
7. Provide unique values for the 'S3_Grade' column.
8. Provide descriptive statistics for all columns in df4.
9. Delete the column 'S4_Grade' .
10. Create the 'Diff_S1-S2' that shows difference between S1 and S2.
11. Create df5 data frame consisting of 'Name' and 'Diff_S1-S2'.
12. Save df5 to the file 'df5.csv'.
13. Download the file and upload it to your github repository.
14. Submit the raw link to the file as a response to this challenge.
"""

import pandas as pd

df4=pd.read_csv("https://raw.githubusercontent.com/bartpiel/files-for-classes/refs/heads/main/Workshop-1/S1_Student_Grades_2.csv")

# Select the first 7 rows
df4.head(7)

# Select 9 random rows
df4.sample(9)

# Provide names of all df4 columns
df4.columns

# Calculate the mean for 'S1_Grade' column
df4['S1_Grade'].mean()

# Calculate the median for 'S4_Grade' column
df4['S4_Grade'].median()

# Provide unique values for 'S3_Grade' column
df4['S3_Grade'].unique()

# Provide descriptive statistics for all columns in df4
df4.describe()

# Drop column 'S4_Grade'
df4=df4.drop(columns=["S4_Grade"])
df4.columns

# Create a new column
df4["Diff_S1-S2"]=df4["S1_Grade"]-df4["S2_Grade"]
df4.head(5)

# Create a new data frame
df5=df4[['Name','Diff_S1-S2']]
df5.head(10)

# Save your new data frame as a CSV file
df5.to_csv("df5.csv")

